# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      npm --prefix client install
    displayName: "Install Node dependencies in frontend"

  - script: |
      npm --prefix client run build
    displayName: "Building the frontend"

  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'client'
      Contents: '!(**/dist/*)'
      RemoveSourceFolder: false
      RemoveDotFiles: true
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students(f2e395ec-82cd-4beb-befa-76bd5ce082d1)'
      appType: 'webApp'
      appName: 'ServeSpot'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      deploymentMethod: 'auto'