# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

variables:
  uiSource: 'client'
  uiBuild: '$(uiSource)/dist'
  appRoot: ''

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - script: |
      pwd
      ls
      npm i
    displayName: "Server Install"

  - script: |
      pushd $(uiSource)
      npm install
      npm run build
      popd
    displayName: "Install Node dependencies in frontend and build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure for Students (ddc1cb0e-7021-43ee-88f7-3f7c9cda3828)'
      appType: 'webApp'
      appName: 'ServeSpot'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      deploymentMethod: 'auto'