trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: "Build"
    displayName: "Build and Test"
    jobs:
      - job: "Build"
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js v20"
            inputs:
              versionSpec: "20.x"

          - script: |
              npm --prefix client install
            displayName: "Install frontend dependencies"

          - script: |
              npm --prefix client run build
            displayName: "Build the frontend"

          - task: CopyFiles@2
            displayName: "Copy build"
            inputs:
              contents: "client/dist/**"
              targetFolder: "$(Build.ArtifactStagingDirectory)"

          - script: |
              npm install
            displayName: "Install Node dependencies in server"

          - task: CopyFiles@2
            inputs:
              contents: |
                .env
                package.json
                server.js
                server/**
                database/**
                node_modules/**
              targetFolder: "$(Build.ArtifactStagingDirectory)"
            displayName: "Copy server components"

          - publish: "$(Build.ArtifactStagingDirectory)"
            displayName: "Publish App for Deployment"
            artifact: dropApp

  - stage: "Deploy"
    displayName: "Deploy to Azure App"
    dependsOn: "Build"
    jobs:
      - job: "Deploy"
        steps:
          - download: current
            artifact: dropApp

          - task: ArchiveFiles@2
            displayName: "Packaging files into zip"
            inputs:
              rootFolderOrFile: "$(Pipeline.Workspace)/dropApp"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/drop.zip"
              replaceExistingArchive: true

          - task: AzureWebApp@1
            inputs:
              azureSubscription: "ServeSpot-RM"
              appType: "webApp"
              appName: "ServeSpot"
              package: "$(Build.ArtifactStagingDirectory)/*.zip"
              customWebConfig: "-appType node"
              deploymentMethod: "runFromPackage"
