POST http://localhost:3000/api/register
content-type: application/json

{
    "email":"monkey@.com",
    "password":"hello",
    "name":"Balls"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"ape@",
    "password":"help"
}
### 
POST http://localhost:3000/api/test
Content-Type: application/json
Autherization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFwZUAiLCJpYXQiOjE3MDk1Njc2NDAsImV4cCI6MTcwOTU2ODU0MH0.wZFA-AyEuy3BsqKCchSQZXfF9yHdgYkWBZkIWC_rp_c

{

}